### PR TITLE
Fix another source of OOM in _destroyedObjects handling (PR #4 followup)

### PR DESCRIPTION
**Pull request by gsnewmark**
Even after switching to new version of the aleph/dirigiste (with merged PR #4) OOM due to the uncontrolled growth of [`io.aleph.dirigiste.Pool::_destroyedObjects`](https://github.com/ztellman/dirigiste/blob/e25834bce7ccaec5b9cd8626f1f02207d93b3b4d/src/io/aleph/dirigiste/Pool.java#L205) could still be reproduced (although it needs longer period of time to fill the memory). 

I've ran few simple tests with additional debug statements added to the [`dispose`](https://github.com/ztellman/dirigiste/blob/e25834bce7ccaec5b9cd8626f1f02207d93b3b4d/src/io/aleph/dirigiste/Pool.java#L440) and something strange was happening: out of 6509 calls to the `dispose` 2931 followed the [`cleanup` branch](https://github.com/ztellman/dirigiste/blob/e25834bce7ccaec5b9cd8626f1f02207d93b3b4d/src/io/aleph/dirigiste/Pool.java#L452), but disposed object was actually cleaned (removed from the `_destroyedObjects`) only 172 times. In all other cases neither [`_start`](https://github.com/ztellman/dirigiste/blob/e25834bce7ccaec5b9cd8626f1f02207d93b3b4d/src/io/aleph/dirigiste/Pool.java#L206) nor queue's [`_puts`](https://github.com/ztellman/dirigiste/blob/e25834bce7ccaec5b9cd8626f1f02207d93b3b4d/src/io/aleph/dirigiste/Pool.java#L16) contained the disposed object, so it remained in the `_destroyedObjects` forever. I've tried to run `dispose` logic in the same critical section as the `cleanup` (by sharing the same lock in both methods and not [unlocking it](https://github.com/ztellman/dirigiste/blob/e25834bce7ccaec5b9cd8626f1f02207d93b3b4d/src/io/aleph/dirigiste/Pool.java#L446) in the `dispose`) but results were basically the same. 

For now I can't really understand what could be the reason of such behavior (maybe object is not added to the queue (`_puts`) at all or it's removed from queue but `_start` doesn't get populated), so this is more an issue report than a PR. 

As a temporary solution I simply explicitly remove the object to be disposed from the `_destroyedObjects` during the `cleanup` if it wasn't found in the queue: memory leak disappeared, but I'm not sure it's correct for all the possible cases (for instance, I'm not sure whether the [`objects`](https://github.com/ztellman/dirigiste/blob/e9f4929cfa9c28dea4fff717005d9f3c13f71c37/src/io/aleph/dirigiste/Pool.java#L22) should be decremented).

Test scenario was running the same HTTP request concurrently in a loop with a short timeout (so most of the requests failed).

### CODE REVIEW

**Comment by ztellman** [comment]
Okay, I'm going write some stress tests that don't require Aleph, and see if I can actually zero in on what's going on.  Thank you for the detailed reports.

**Comment by gsnewmark** [comment]
Thanks. Initially I thought that problem is somewhere in the Dirigiste and didn't look in the Aleph's source, but after today's investigation I have a feeling that it could be Aleph supplying the same connection to the `dispose` for few times: the first time it would be destroyed & removed from queue normally, but for all the next `dispose` calls such connection would simply be added to the `_destroyedObjects` set (if it's not already there) because `_start` and `_puts` won't have it anymore. 

Is such situation possible? I don't have time right know, but will check this later.

**Comment by ztellman** [comment]
`dispose` is meant to be idempotent, so that should be okay if it's happening (and it definitely can, since two different code paths can call it).

**Comment by gsnewmark** [comment]
I probably was a bit vague in the last comment. I've tried to say that, if I understand correctly, currently `dispose` is not really idempotent: each consecutive call with the same object won't remove it from the pool more than once (this part is truly idempotent :smile:), but at the same time internal state of the pool **would** change after the second call (although not after the next ones). Object would be [added to the `_destroyedObjects`](https://github.com/ztellman/dirigiste/blob/e9f4929cfa9c28dea4fff717005d9f3c13f71c37/src/io/aleph/dirigiste/Pool.java#L444) once again, and would remain there forever, because it was removed from the `_start` and/or queue's `_puts` during the first call, so this object can't be removed from the `_destroyedObjects` during [`q.put(obj)`](https://github.com/ztellman/dirigiste/blob/e9f4929cfa9c28dea4fff717005d9f3c13f71c37/src/io/aleph/dirigiste/Pool.java#L100) (this method simply wouldn't be called) and [`q.cleanup()`](https://github.com/ztellman/dirigiste/blob/e9f4929cfa9c28dea4fff717005d9f3c13f71c37/src/io/aleph/dirigiste/Pool.java#L128) (object wouldn't be found in the queue) respectively. 

To ilustrate this problem I created the [repo with simple example scenario](https://github.com/gsnewmark/dirigiste-oom/blob/f4aa44ef42dd30f29eb3af49932c7dea2168b084/src/dirigiste_oom/core.clj). It's a bit hacky (uses reflection to check the `_destroyedObjects`), but tests only the Dirigiste without other moving parts (basically it's a loop which calls `acquire` & `dispose` for the same key). Sample output:
```
⇒  lein run
Dispose each object only once
_destroyedObjects size before check 0
_destroyedObjects size after check 0

Dispose each object twice
_destroyedObjects size before check 0
_destroyedObjects size after check 1000
```

**Comment by ztellman** [comment]
Well, that's certainly not intentional.  I'm going to spend some time this evening writing up a better test suite and see what I find.

**Comment by ztellman** [comment]
Okay, I had misremembered my intent: it was okay for `dispose()` to be called and then `release()` for the same object, but not `dispose()` twice.  I could call this a bug in Aleph, but I'm leaning towards just turning `_destroyedObjects` into a weak set and calling it solved.  Any problems you can see with that?

**Comment by gsnewmark** [comment]
I think switching to the weak set should solve the problem. There shouldn't be any problem with queue's `put`/`cleanup`/`take`, because if `obj` is still in the `_puts`/`_start` it wouldn't be removed from the `_destroyedObjects` automatically, so logic of `put`/`cleanup`/`take` wouldn't be altered, and if `dispose` is called for the second time when `obj` is already 'cleaned' weak set would simply autoremove it during one of the next GC calls.

Just to be extra sure I've ran the same artificial test (based on the Aleph client) I've used to reproduce the OOM using the `[io.aleph/dirigiste "0.1.2-alpha1"]` with the following change
```diff
modified   src/io/aleph/dirigiste/Pool.java
@@ -202,7 +202,8 @@ public class Pool<K,V> implements IPool<K,V> {
 
     private final AtomicInteger _numObjects = new AtomicInteger(0);
     private final ReentrantLock _lock = new ReentrantLock();
-    private final Set<V> _destroyedObjects = Collections.synchronizedSet(new HashSet<V>());
+    private final Set<V> _destroyedObjects =
+        Collections.synchronizedSet(Collections.newSetFromMap(new WeakHashMap<V, Boolean>()));
     private final ConcurrentHashMap<V,Long> _start = new ConcurrentHashMap<V,Long>();
     private final ConcurrentHashMap<K,Queue> _queues = new ConcurrentHashMap<K,Queue>();
```
and uncontrollable growth of `_destroyedObjects` is not reproduced.

**Comment by ztellman** [comment]
Okay, that matches my test results as well.  I still need a better test suite for Dirigiste, but I'll cut a new alpha release in the meantime.

**Comment by gsnewmark** [comment]
Hi! 
Are you still planning on releasing the new alpha of Dirigiste or something is wrong with weak set approach? I'm using the [fork](https://github.com/gsnewmark/dirigiste/tree/tmp-fix) with [this change](https://github.com/ztellman/dirigiste/pull/5#issuecomment-159234963) applied for the last couple of months, looks OK so far (there were no OOMs during since end of November).

Also, it looks like `0.1.2-alpha1` release is not available on Clojars too.

**Comment by ztellman** [comment]
I've just released `0.1.2`. on Maven, marking it as a dependency should allow you to pull it down.

**Comment by ztellman** [comment]
Sorry, just realized I had deployed to Maven but not pushed the code.  That's fixed now.

**Comment by gsnewmark** [comment]
Thanks!

**Pull request closed without merging**
